@baseUrl = http://localhost:4000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA1YjFiNjY4LWMwZGYtNDQzNS05MWI0LTkwYjI2ODVjYTNlNyIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc3Njk0MzczNywiZXhwIjoxNzc3NTQ4NTM3fQ.2YWkS7wEet3LUnOg5u_JG8BYUbrvANzXfuJ5aBVxGJI
@incidentId = 46236d7a-5d2d-4a43-92d2-243e3558373a

###
GET {{baseUrl}}/health

###
GET {{baseUrl}}/incidents
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/incidents/mine
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/incidents/{{incidentId}}
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/incidents/report
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Test Incident",
  "sector": "Sector 1",
  "severity": "HIGH"
}

###
PATCH {{baseUrl}}/incidents/{{incidentId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Updated Incident Title",
  "description": "Updated by admin",
  "sector": "Sector 2",
  "severity": "CRITICAL"
}

###
PATCH {{baseUrl}}/incidents/{{incidentId}}/status
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "status": "IN_PROGRESS"
}

###
PATCH {{baseUrl}}/incidents/{{incidentId}}/resolve
Content-Type: application/json
Authorization: Bearer {{token}}

###
PATCH {{baseUrl}}/incidents/{{incidentId}}/close
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/incidents/{{incidentId}}
Authorization: Bearer {{token}}